
package Sanjeevani.gui;

import Sanjeevani.pojo.UserProfilePojo;


public class AdminOptionsFrame extends javax.swing.JFrame {

    
    public AdminOptionsFrame() 
    {
        initComponents();
        super.setLocationRelativeTo(null);
        lblName.setText("USER-"+UserProfilePojo.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bntLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMngEmp = new javax.swing.JButton();
        btnMngDoc = new javax.swing.JButton();
        btnMngReceptionists = new javax.swing.JButton();
        btnViewPatients = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Panel");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, -1));

        bntLogout.setBackground(new java.awt.Color(0, 102, 102));
        bntLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bntLogout.setForeground(new java.awt.Color(0, 204, 204));
        bntLogout.setText("Logout");
        bntLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(bntLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 850, 90));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 370, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 410, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Sanjeevani  Application");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 380, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanjeevani/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1090, 540));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HELLO,");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        lblName.setBackground(new java.awt.Color(51, 51, 51));
        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNameActionPerformed(evt);
            }
        });
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 120));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanjeevani/icons/images.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -70, 230, 400));

        btnMngEmp.setBackground(new java.awt.Color(204, 204, 255));
        btnMngEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMngEmp.setText("Manage Employees");
        btnMngEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmpActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 150, 230, 60));

        btnMngDoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMngDoc.setText("Manage Doctors");
        btnMngDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngDocActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 190, 60));

        btnMngReceptionists.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMngReceptionists.setText("Manage Receptionists");
        btnMngReceptionists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngReceptionistsActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngReceptionists, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 60));

        btnViewPatients.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewPatients.setText("View Patients");
        btnViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientsActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 190, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1090, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmpActionPerformed
        // TODO add your handling code here:
      ManageEmployeeFrame manageEmpFrame=new ManageEmployeeFrame();
      manageEmpFrame.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnMngEmpActionPerformed

    private void lblNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNameActionPerformed

    private void bntLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntLogoutActionPerformed

    private void btnMngDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngDocActionPerformed
        // TODO add your handling code here:
       ManageDoctorsFrame docFrame=new ManageDoctorsFrame();
       docFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMngDocActionPerformed

    private void btnMngReceptionistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngReceptionistsActionPerformed
        // TODO add your handling code here:
        ManageReceptionistsFrame RecFrame=new ManageReceptionistsFrame();
        RecFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMngReceptionistsActionPerformed

    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed
        // TODO add your handling code here:
        ViewPatientFrame frame=new ViewPatientFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLogout;
    private javax.swing.JButton btnMngDoc;
    private javax.swing.JButton btnMngEmp;
    private javax.swing.JButton btnMngReceptionists;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lblName;
    // End of variables declaration//GEN-END:variables
}
